In [1]:
# Import Libraries

import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
# Load Dataset

df = pd.read_csv("loan_data.csv")

df

,Loan_ID,Gender,Married,ApplicantIncome,LoanAmount,Credit_History,Loan_Status
0,L001,Male,Yes,5000,150,1,Approved
1,L002,Female,No,3000,100,1,Approved
2,L003,Male,Yes,2500,120,0,Rejected
3,L004,Female,No,6000,200,1,Approved
4,L005,Male,Yes,2000,90,0,Rejected
5,L006,Female,Yes,7000,250,1,Approved
6,L007,Male,No,3500,130,0,Rejected
7,L008,Female,Yes,8000,300,1,Approved

In [3]:
# Convert Loan Status to Numbers

df["Loan_Status"] = df["Loan_Status"].map({
    "Approved":1,
    "Rejected":0
})

df

,Loan_ID,Gender,Married,ApplicantIncome,LoanAmount,Credit_History,Loan_Status
0,L001,Male,Yes,5000,150,1,1
1,L002,Female,No,3000,100,1,1
2,L003,Male,Yes,2500,120,0,0
3,L004,Female,No,6000,200,1,1
4,L005,Male,Yes,2000,90,0,0
5,L006,Female,Yes,7000,250,1,1
6,L007,Male,No,3500,130,0,0
7,L008,Female,Yes,8000,300,1,1

In [4]:
# Convert Gender

df["Gender"] = df["Gender"].map({
    "Male":1,
    "Female":0
})

# Convert Married

df["Married"] = df["Married"].map({
    "Yes":1,
    "No":0
})

df

,Loan_ID,Gender,Married,ApplicantIncome,LoanAmount,Credit_History,Loan_Status
0,L001,1,1,5000,150,1,1
1,L002,0,0,3000,100,1,1
2,L003,1,1,2500,120,0,0
3,L004,0,0,6000,200,1,1
4,L005,1,1,2000,90,0,0
5,L006,0,1,7000,250,1,1
6,L007,1,0,3500,130,0,0
7,L008,0,1,8000,300,1,1

In [5]:
# Features and Target

X = df[
    [
        "Gender",
        "Married",
        "ApplicantIncome",
        "LoanAmount",
        "Credit_History"
    ]
]

y = df["Loan_Status"]

print(X.head())
print(y.head())

   Gender  Married  ApplicantIncome  LoanAmount  Credit_History
0       1        1             5000         150               1
1       0        0             3000         100               1
2       1        1             2500         120               0
3       0        0             6000         200               1
4       1        1             2000          90               0
0    1
1    1
2    0
3    1
4    0
Name: Loan_Status, dtype: int64

In [6]:
# Train Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Split Completed")

Split Completed

In [7]:
# Train Model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [8]:
# Predictions

predictions = model.predict(X_test)

print(predictions)

[0 1]

In [9]:
# Accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

Accuracy: 0.5

In [10]:
# New Applicant Prediction

new_applicant = [[1,1,5500,180,1]]

result = model.predict(new_applicant)

if result[0] == 1:
    print("Loan Approved")
else:
    print("Loan Rejected")

Loan Approved

c:\Users\Jahnavi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [11]:
# Save Report

df.to_csv("loan_report.csv", index=False)

print("Report Saved Successfully")

Report Saved Successfully